SELECT * FROM Pazienti;
SELECT * FROM Medici;
SELECT * FROM Ricoveri;
SELECT COUNT(*) FROM Pazienti WHERE Genere = 'Femmina';
SELECT Genere, COUNT(*) AS Numero_di_pazienti FROM Pazienti GROUP BY Genere;
SELECT strftime('%Y', Data_ricovero) AS Anno, 'Primo Semestre' AS Semestre, COUNT(*) AS Numero_Ricoveri FROM Ricoveri WHERE strftime('%m', Data_ricovero) BETWEEN '01' AND '06' GROUP BY strftime('%Y', Data_ricovero) UNION ALL SELECT strftime('%Y', Data_ricovero) AS Anno, 'Secondo Semestre' AS Semestre, COUNT(*) AS Numero_Ricoveri FROM Ricoveri WHERE strftime('%m', Data_ricovero) BETWEEN '07' AND '12' GROUP BY strftime('%Y', Data_ricovero);
SELECT strftime('%Y', Data_ricovero) AS Anno, COUNT(*) AS Numero_Scansioni FROM Procedure WHERE Descrizione LIKE '%MRI%' OR Descrizione LIKE '%CT%' GROUP BY strftime('%Y', Data_ricovero);
SELECT strftime('%Y', Data_ricovero) AS Anno, COUNT(*) AS Numero_Vaccinazioni FROM Procedure WHERE Descrizione LIKE '%vaccinazione%' OR Descrizione LIKE '%vaccino%' GROUP BY strftime('%Y', Data_ricovero);
SELECT Reparti.nome_reparto, Medici.Nome AS Capo_Dipartimento FROM Reparti JOIN Medici ON Reparti.direttore_reparto = Medici.ID_medico;
SELECT * FROM Reparti WHERE nome_reparto LIKE '%ologia%';
SELECT Nome, Indirizzo FROM Medici WHERE Genere = 'Maschio';
SELECT Procedure.* FROM Procedure JOIN Ricoveri ON Procedure.ID_ricovero = Ricoveri.ID_ricovero JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Nome = 'Olivia Davis';
SELECT * FROM Procedure WHERE Descrizione LIKE '%intervento chirurgico%';
SELECT Trattamenti.* FROM Trattamenti JOIN Ricoveri ON Trattamenti.ID_ricovero = Ricoveri.ID_ricovero JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Linda Garcia';
SELECT Nome, Telefono, Email FROM Medici WHERE Genere = 'Maschio';
SELECT Data_ricovero, Data_dimissione FROM Ricoveri JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'James Miller';
SELECT Ricoveri.Data_ricovero, Ricoveri.Data_dimissione FROM Ricoveri JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'pediatria';
SELECT Reparti.nome_reparto, Medici.Nome AS Capo_Dipartimento FROM Reparti JOIN Medici ON Reparti.direttore_reparto = Medici.ID_medico WHERE Reparti.telefono LIKE '%555%';
SELECT Ricoveri.Diagnosi, Trattamenti.Descrizione AS Trattamento FROM Ricoveri JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente JOIN Trattamenti ON Ricoveri.ID_ricovero = Trattamenti.ID_ricovero WHERE Pazienti.Nome = 'Barbara Martinez';
SELECT DISTINCT Medici.Email, Medici.Telefono FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE Ricoveri.Diagnosi LIKE '%ipertensione%';
SELECT Email FROM Medici WHERE Specializzazione = 'neurologia';
SELECT Email FROM Pazienti;
SELECT Nome, Indirizzo FROM Medici WHERE Genere = 'Maschio';
SELECT Pazienti.Nome, Pazienti.Indirizzo FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.Diagnosi = 'BPCO';
SELECT Pazienti.Nome, Pazienti.Indirizzo FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Nome = 'Mia Wilson';
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'neurologia';
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE julianday(Ricoveri.Data_dimissione) - julianday(Ricoveri.Data_ricovero) <= 3;
SELECT NominativoContattoEmergenza, TelefonoContattoEmergenza FROM Pazienti WHERE Nome = 'Linda Garcia';
SELECT Pazienti.Nome, Ricoveri.Diagnosi FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Medici.Nome = 'Ava Rodriguez' AND Reparti.nome_reparto = 'Pediatria';
SELECT Pazienti.Nome, Ricoveri.Diagnosi FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE DATE('now', '-8 weeks') <= Ricoveri.Data_ricovero;
SELECT Pazienti.Nome, Ricoveri.Diagnosi FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.Diagnosi LIKE '%diabete%' AND Ricoveri.Diagnosi LIKE '%ipertensione%';
SELECT Nome, Email FROM Medici WHERE Genere = 'Femmina';
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'oncologia';
SELECT Pazienti.Nome, Pazienti.Email FROM Pazienti WHERE RelazioneContattoEmergenza = 'coniuge';
SELECT Nome, Telefono FROM Medici WHERE Genere = 'Maschio';
SELECT Nome, Telefono FROM Pazienti WHERE julianday('now') - julianday(Data_nascita) > 365 * 65;
SELECT Nome, Telefono FROM Pazienti WHERE strftime('%Y-%m', Data_ricovero) = '2024-01';
SELECT DISTINCT Medici.Nome, Medici.Telefono FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE Ricoveri.Diagnosi LIKE '%ipertensione%';
SELECT Pazienti.Nome, Pazienti.Telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto IN ('emergenza', 'ortopedia');
SELECT Pazienti.Nome, Pazienti.Telefono FROM Pazienti JOIN Trattamenti ON Pazienti.ID_paziente = Trattamenti.ID_ricovero WHERE Trattamenti.Descrizione LIKE '%terapia fisica%';
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE strftime('%Y-%m', Data_ricovero) = '2023-01' AND Medici.Specializzazione = 'medicina di emergenza';
SELECT Nome, Numero_di_telefono FROM Pazienti WHERE RelazioneContattoEmergenza IN ('fratello', 'sorella');
SELECT Nome, Numero_di_telefono FROM Pazienti WHERE NominativoContattoEmergenza LIKE 'John%';
SELECT Medici.Nome, Medici.Specializzazione FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'neurologia';
SELECT nome_reparto FROM Reparti WHERE nome_reparto LIKE '%emergenza%';
SELECT Medici.Nome FROM Medici WHERE Medici.ID_medico IN (SELECT DISTINCT Ricoveri.ID_medico FROM Ricoveri JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'oncologia') AND Medici.ID_medico IN (SELECT DISTINCT Ricoveri.ID_medico FROM Ricoveri JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'gastroenterologia');
SELECT Nome FROM Medici WHERE Specializzazione = 'cardiologia';
SELECT Nome FROM Pazienti WHERE Genere = 'Femmina';
SELECT Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.Diagnosi LIKE '%diabete%';
SELECT Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Nome = 'Ethan Martinez';
SELECT Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'pediatria';
SELECT Nome FROM Medici WHERE ID_medico NOT IN (SELECT DISTINCT ID_medico FROM Ricoveri WHERE Data_ricovero >= DATE('now', '-6 months'));
SELECT Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'neurologia' AND Ricoveri.Diagnosi = 'epilessia';
SELECT Procedure.Descrizione FROM Procedure JOIN Ricoveri ON Procedure.ID_ricovero = Ricoveri.ID_ricovero JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Barbara Brown';
SELECT Ricoveri.ID_ricovero, Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Trattamenti ON Ricoveri.ID_ricovero = Trattamenti.ID_ricovero GROUP BY Ricoveri.ID_ricovero, Pazienti.Nome HAVING COUNT(Trattamenti.Descrizione) > 1;
SELECT strftime('%Y', Data_ricovero) AS Anno, AVG(julianday(Data_dimissione) - julianday(Data_ricovero)) AS DurataMedia FROM Ricoveri WHERE strftime('%Y', Data_ricovero) IN ('2022', '2023', '2024') GROUP BY strftime('%Y', Data_ricovero);
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE DATE('now', '-3 months') <= Ricoveri.Data_ricovero;
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'neurologia' AND strftime('%Y', Ricoveri.Data_ricovero) = '2023';
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE strftime('%Y-%m', Ricoveri.Data_ricovero) = '2024-05' AND strftime('%Y-%m', Ricoveri.Data_dimissione) = '2024-06';
SELECT Medici.Nome, Medici.Email FROM Medici WHERE Medici.ID_medico IN (SELECT DISTINCT ID_medico FROM Ricoveri WHERE (strftime('%Y-%m', Data_ricovero) BETWEEN '2023-01' AND '2023-06') OR (strftime('%Y-%m', Data_ricovero) BETWEEN '2024-01' AND '2024-06'));
SELECT DISTINCT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto != Medici.Specializzazione;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Specializzazione = 'cardiologia';
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Ricoveri.Data_ricovero >= DATE('now', '-1 year');
SELECT DISTINCT Medici.Nome, Medici.Specializzazione FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE strftime('%Y-%m', Ricoveri.Data_ricovero) = '2024-01';
SELECT DISTINCT Medici.Nome, Medici.Specializzazione FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE strftime('%Y-%m', Ricoveri.Data_ricovero) = '2024-01';
SELECT Reparti.nome_reparto, Medici.Nome AS Capo_Dipartimento FROM Reparti JOIN Medici ON Reparti.direttore_reparto = Medici.ID_medico WHERE Medici.Specializzazione = 'Neurologia';
SELECT * FROM Ricoveri WHERE ID_paziente = (SELECT ID_paziente FROM Pazienti WHERE Nome = 'Richard Martinez');
SELECT Trattamenti.* FROM Trattamenti JOIN Ricoveri ON Trattamenti.ID_ricovero = Ricoveri.ID_ricovero WHERE Ricoveri.ID_paziente = (SELECT ID_paziente FROM Pazienti WHERE Nome = 'Richard Martinez');
SELECT * FROM Trattamenti WHERE Descrizione LIKE '%terapia%';
SELECT Nome, Numero_di_telefono FROM Pazienti WHERE strftime('%Y', Data_ricovero) = '2023';
SELECT Indirizzo FROM Medici WHERE Indirizzo LIKE '%strada%';
SELECT Data_ricovero, Data_dimissione FROM Ricoveri WHERE ID_paziente = (SELECT ID_paziente FROM Pazienti WHERE Nome = 'Barbara Brown');
SELECT Ricoveri.Data_ricovero, Medici.Nome FROM Ricoveri JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'pediatria';
SELECT Data_ricovero FROM Ricoveri WHERE strftime('%Y', Data_ricovero) = '2023';
SELECT Data_ricovero FROM Ricoveri JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'emergenza';
SELECT Data_di_nascita FROM Medici WHERE Nome = 'Michael Brown';
SELECT Ricoveri.Diagnosi, Trattamenti.Descrizione FROM Ricoveri JOIN Trattamenti ON Ricoveri.ID_ricovero = Trattamenti.ID_ricovero JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Nome = 'Emma Young';
SELECT Ricoveri.Diagnosi, Farmaci.Descrizione FROM Ricoveri JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero WHERE ID_paziente = (SELECT ID_paziente FROM Pazienti WHERE Nome = 'Robert Rodriguez');
SELECT Diagnosi FROM Ricoveri WHERE ID_paziente = (SELECT ID_paziente FROM Pazienti WHERE Nome = 'Elizabeth Miller');
SELECT Email FROM Pazienti WHERE Genere = 'Femmina';
SELECT Farmaci.Descrizione FROM Farmaci JOIN Ricoveri ON Farmaci.ID_ricovero = Ricoveri.ID_ricovero JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Jennifer Miller';
SELECT Farmaci.Descrizione FROM Farmaci JOIN Ricoveri ON Farmaci.ID_ricovero = Ricoveri.ID_ricovero JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'radiologia';
SELECT Farmaci.Descrizione FROM Farmaci JOIN Ricoveri ON Farmaci.ID_ricovero = Ricoveri.ID_ricovero JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Margaret Jones';
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Reparti ON Medici.ID_medico = Reparti.direttore_reparto WHERE Reparti.nome_reparto = 'cardiologia';
SELECT Pazienti.Nome, Pazienti.Indirizzo FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.Data_ricovero >= DATE('now', '-6 months');
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE strftime('%Y-%m', Ricoveri.Data_ricovero) = (SELECT strftime('%Y-%m', Data_ricovero) FROM Ricoveri JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Joseph Garcia');
SELECT DISTINCT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Procedure ON Ricoveri.ID_ricovero = Procedure.ID_ricovero WHERE Procedure.Descrizione LIKE '%intervento chirurgico%';
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE (strftime('%Y', Ricoveri.Data_ricovero) = '2022' OR strftime('%Y', Ricoveri.Data_ricovero) = '2023') AND Pazienti.ID_paziente IN (SELECT ID_paziente FROM Ricoveri WHERE strftime('%Y-%m', Data_ricovero) BETWEEN '2024-01' AND '2024-06');
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE strftime('%Y-%m', Ricoveri.Data_ricovero) = (SELECT strftime('%Y-%m', Data_ricovero) FROM Ricoveri JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Joseph Garcia');
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE strftime('%Y-%m', Data_ricovero) = strftime('%Y-%m', Data_dimissione);
SELECT DISTINCT Medici.Nome, Medici.Data_di_nascita FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE strftime('%Y', Ricoveri.Data_ricovero) = '2023';
SELECT Ricoveri.Diagnosi FROM Ricoveri JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Jennifer Brown';
SELECT Pazienti.Nome, Ricoveri.Diagnosi FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Medici.Nome = 'Ava Rodriguez' AND Reparti.nome_reparto = 'Pediatria';
SELECT Nome, Email FROM Medici WHERE Indirizzo LIKE '%Metropolis%';
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE Ricoveri.Diagnosi LIKE '%diabete%';
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE Ricoveri.Diagnosi LIKE '%diabete%';
SELECT Reparti.nome_reparto, Medici.Nome FROM Reparti JOIN Medici ON Reparti.direttore_reparto = Medici.ID_medico WHERE Reparti.telefono IS NOT NULL;
SELECT DISTINCT Medici.Nome, Medici.Telefono FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'oncologia';
SELECT Nome, Telefono FROM Medici WHERE Specializzazione = 'pediatria';
SELECT Pazienti.Nome, Pazienti.Telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto IN ('emergenza', 'ortopedia');
SELECT DISTINCT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'oncologia' AND Pazienti.ID_paziente IN (SELECT Ricoveri.ID_paziente FROM Ricoveri JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'radiologia');
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'emergenza' AND Ricoveri.Data_ricovero >= DATE('now', '-1 year');
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Specializzazione = 'ortopedia';
SELECT Medici.Nome, Medici.Specializzazione FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'oncologia';
SELECT Medici.Nome, Medici.Specializzazione FROM Medici WHERE Medici.ID_medico IN (SELECT DISTINCT Ricoveri.ID_medico FROM Ricoveri JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'neurologia') AND Medici.ID_medico IN (SELECT DISTINCT Ricoveri.ID_medico FROM Ricoveri JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'oncologia');
SELECT Nome, Specializzazione FROM Medici WHERE Data_di_nascita < '1970-01-01';
SELECT Pazienti.Nome, Pazienti.Data_nascita, GROUP_CONCAT(Farmaci.Descrizione) AS Farmaci FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero GROUP BY Pazienti.Nome, Pazienti.Data_nascita HAVING COUNT(Farmaci.Descrizione) > 1;
SELECT nome_reparto FROM Reparti JOIN Medici ON Reparti.direttore_reparto = Medici.ID_medico WHERE Medici.Specializzazione = 'cardiologia';
SELECT nome_reparto FROM Reparti;
SELECT Nome FROM Pazienti WHERE Genere = 'maschio';
SELECT Pazienti.Nome, Ricoveri.Data_ricovero, Ricoveri.Data_dimissione FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE strftime('%Y-%m', Data_ricovero) = '2024-01';
SELECT Nome FROM Pazienti WHERE (julianday('now') - julianday(Data_nascita))/365 >= 50;
SELECT Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Data_ricovero = '2023-11-03';
SELECT Medici.Nome, Ricoveri.Data_ricovero FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Linda Johnson' AND strftime('%Y', Ricoveri.Data_ricovero) = '2023';
SELECT Medici.Nome, Medici.Specializzazione FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE Ricoveri.Diagnosi LIKE '%ictus%';
SELECT Nome FROM Medici WHERE Data_di_nascita BETWEEN '1970-01-01' AND '1980-12-31';
SELECT Nome FROM Medici WHERE Specializzazione = 'neurologia';
SELECT Ricoveri.Data_ricovero, Ricoveri.Diagnosi FROM Ricoveri WHERE Diagnosi LIKE '%malattia%';
SELECT Numero_di_telefono, Indirizzo FROM Pazienti WHERE Nome = 'Elizabeth Jones';
SELECT Reparti.telefono, Reparti.email FROM Reparti;
SELECT Procedure.* FROM Procedure JOIN Ricoveri ON Procedure.ID_ricovero = Ricoveri.ID_ricovero JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Nome = 'Emily White';
SELECT Specializzazione FROM Medici WHERE Specializzazione LIKE '%intervento chirurgico%';
SELECT Trattamenti.Descrizione AS Trattamento, Procedure.Descrizione AS Procedura FROM Trattamenti JOIN Procedure ON Trattamenti.ID_ricovero = Procedure.ID_ricovero JOIN Ricoveri ON Trattamenti.ID_ricovero = Ricoveri.ID_ricovero JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'Maria Rodriguez';
SELECT strftime('%Y', Data_ricovero) AS Anno, AVG(julianday(Data_dimissione) - julianday(Data_ricovero)) AS DurataMedia FROM Ricoveri JOIN Procedure ON Ricoveri.ID_ricovero = Procedure.ID_ricovero WHERE Procedure.Descrizione LIKE '%intervento chirurgico%' GROUP BY strftime('%Y', Data_ricovero);
SELECT AVG(julianday(Data_dimissione) - julianday(Data_ricovero)) AS DurataMedia FROM Ricoveri;
SELECT Pazienti.Nome, Farmaci.Descrizione AS Farmaco, Reparti.nome_reparto FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Ricoveri.Diagnosi = 'BPCO';
SELECT Medici.Specializzazione, AVG(julianday(Ricoveri.Data_dimissione) - julianday(Ricoveri.Data_ricovero)) AS DurataMedia FROM Ricoveri JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico GROUP BY Medici.Specializzazione ORDER BY DurataMedia DESC;
SELECT COUNT(*) AS NumeroInterventi, GROUP_CONCAT(Farmaci.Descrizione) AS Farmaci FROM Procedure JOIN Farmaci ON Procedure.ID_ricovero = Farmaci.ID_ricovero WHERE Procedure.Descrizione LIKE '%sostituzione dell\'anca%';
SELECT COUNT(*) AS AmmissioniInCorso, Reparti.nome_reparto FROM Ricoveri JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Data_dimissione IS NULL;
SELECT COUNT(*) AS NumeroPazienti FROM Procedure WHERE Descrizione LIKE '%intervento chirurgico%' AND strftime('%Y', Data_ricovero) = '2022';
SELECT Medici.Nome, Medici.Età, Medici.Genere, GROUP_CONCAT(DISTINCT Pazienti.Nome) AS Pazienti, GROUP_CONCAT(DISTINCT Farmaci.Descrizione) AS Farmaci FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero WHERE Medici.Specializzazione = 'anestesiologia' GROUP BY Medici.Nome, Medici.Età, Medici.Genere;
SELECT Ricoveri.Diagnosi, COUNT(*) AS NumeroAmmissioni FROM Ricoveri WHERE strftime('%Y', Data_ricovero) = '2024' GROUP BY Ricoveri.Diagnosi ORDER BY NumeroAmmissioni DESC;
SELECT DISTINCT Medici.Nome, Medici.Email FROM Medici WHERE Medici.ID_medico IN (SELECT DISTINCT ID_medico FROM Ricoveri WHERE ID_reparto IN (SELECT ID_reparto FROM Reparti WHERE nome_reparto = 'oncologia') AND ID_medico IN (SELECT DISTINCT ID_medico FROM Ricoveri WHERE ID_reparto IN (SELECT ID_reparto FROM Reparti WHERE nome_reparto = 'gastroenterologia')));
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.ID_medico IN (SELECT ID_medico FROM Medici WHERE Genere IN ('maschio', 'femmina'));
SELECT Medici.Nome, Medici.Specializzazione FROM Medici WHERE Medici.ID_medico IN (SELECT ID_medico FROM Ricoveri WHERE ID_ricovero IN (SELECT ID_ricovero FROM Farmaci WHERE Descrizione = 'aspirina'));
SELECT Pazienti.Nome, Ricoveri.Diagnosi, GROUP_CONCAT(Farmaci.Descrizione) AS Farmaci FROM Ricoveri JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero WHERE Medici.Nome = 'Benjamin Walker' AND Reparti.nome_reparto = 'oncologia' GROUP BY Pazienti.Nome, Ricoveri.Diagnosi;
SELECT Pazienti.Nome, Ricoveri.Diagnosi, Trattamenti.Descrizione AS Trattamento FROM Ricoveri JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente JOIN Trattamenti ON Ricoveri.ID_ricovero = Trattamenti.ID_ricovero WHERE Ricoveri.Diagnosi LIKE '%infezione%';
SELECT Medici.Nome, Medici.Email, Medici.Telefono, Reparti.nome_reparto FROM Medici JOIN Reparti ON Medici.ID_medico = Reparti.direttore_reparto;
SELECT Pazienti.Nome, Pazienti.Telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.ID_medico IN (SELECT ID_medico FROM Medici WHERE Specializzazione = 'cardiologia');
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.ID_reparto = (SELECT ID_reparto FROM Ricoveri JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Pazienti.Nome = 'James Garcia' ORDER BY Ricoveri.Data_ricovero LIMIT 1);
SELECT DISTINCT Farmaci.Descrizione, Pazienti.Nome, Pazienti.Data_nascita FROM Farmaci JOIN Ricoveri ON Farmaci.ID_ricovero = Ricoveri.ID_ricovero JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente WHERE Ricoveri.ID_medico IN (SELECT ID_medico FROM Medici WHERE Nome = 'Mia Wilson');
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Specializzazione = 'cardiologia';
SELECT DISTINCT Medici.Nome FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE Ricoveri.ID_reparto IN (SELECT ID_reparto FROM Reparti WHERE nome_reparto = 'ortopedia');
SELECT Reparti.nome_reparto, COUNT(*) AS NumeroAmmissioni FROM Reparti JOIN Ricoveri ON Reparti.ID_reparto = Ricoveri.ID_reparto WHERE DATE('now', '-2 months') <= Data_ricovero GROUP BY Reparti.nome_reparto;
SELECT Reparti.nome_reparto, COUNT(DISTINCT Medici.ID_medico) AS NumeroMedici FROM Reparti JOIN Medici ON Reparti.direttore_reparto = Medici.ID_medico GROUP BY Reparti.nome_reparto;
SELECT Medici.Nome, COUNT(*) AS NumeroPazienti FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE Ricoveri.Diagnosi LIKE '%ipertensione%' GROUP BY Medici.Nome;
SELECT Medici.Nome, COUNT(DISTINCT Ricoveri.ID_paziente) AS NumeroPazienti FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome;
SELECT Pazienti.Nome, Medici.Specializzazione FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Medici.Specializzazione = 'cardiologia';
SELECT Pazienti.Nome, Ricoveri.Data_ricovero, GROUP_CONCAT(Farmaci.Descrizione) AS Farmaci FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero WHERE Ricoveri.ID_medico = (SELECT ID_medico FROM Medici WHERE Nome = 'Ethan Martinez') AND Procedure.Descrizione LIKE '%intervento chirurgico%' GROUP BY Pazienti.Nome, Ricoveri.Data_ricovero;
SELECT Pazienti.Nome, Ricoveri.Data_ricovero, GROUP_CONCAT(Farmaci.Descrizione) AS Farmaci FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero WHERE Medici.Specializzazione = 'pediatria' GROUP BY Pazienti.Nome, Ricoveri.Data_ricovero;
SELECT Pazienti.Nome, Ricoveri.Data_ricovero, Procedure.Descrizione AS Procedura FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Procedure ON Ricoveri.ID_ricovero = Procedure.ID_ricovero WHERE strftime('%Y-%m', Data_ricovero) = '2023-01' AND strftime('%Y-%m', Data_dimissione) = '2023-02';
SELECT Reparti.nome_reparto, COUNT(*) AS NumeroAmmissioni FROM Reparti JOIN Ricoveri ON Reparti.ID_reparto = Ricoveri.ID_reparto GROUP BY Reparti.nome_reparto;
SELECT strftime('%m', Data_ricovero) AS Mese, COUNT(*) AS NumeroAmmissioni FROM Ricoveri GROUP BY Mese ORDER BY NumeroAmmissioni DESC LIMIT 1;
SELECT Farmaci.Descrizione, COUNT(*) AS Frequenza FROM Farmaci GROUP BY Farmaci.Descrizione ORDER BY Frequenza DESC LIMIT 1;
SELECT Procedure.Descrizione, COUNT(*) AS Frequenza FROM Procedure GROUP BY Procedure.Descrizione ORDER BY Frequenza DESC LIMIT 1;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono, Reparti.nome_reparto FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto GROUP BY Pazienti.Nome, Reparti.nome_reparto HAVING COUNT(Farmaci.Descrizione) > 1;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono, Medici.Nome AS Medico, Reparti.nome_reparto FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto GROUP BY Pazienti.Nome HAVING COUNT(Farmaci.Descrizione) > 2;
SELECT Pazienti.Nome, Pazienti.ID_paziente, Medici.Nome AS Medico, Reparti.nome_reparto FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE strftime('%Y-%m', Ricoveri.Data_ricovero) IN ('2024-05', '2024-06');
SELECT Pazienti.Nome, Farmaci.Descrizione, Medici.Nome AS Prescrittore FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Ricoveri.Diagnosi LIKE '%colpo%' AND Farmaci.Descrizione = 'aspirina';
SELECT Pazienti.Nome, Medici.Nome AS Medico, Reparti.nome_reparto FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Farmaci.Descrizione IN ('eparina', 'enoxaparina');
SELECT Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome HAVING COUNT(*) > 1;
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'cardiologia' GROUP BY Medici.Nome HAVING COUNT(Ricoveri.ID_paziente) > 1;
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome HAVING COUNT(Ricoveri.ID_paziente) > 2;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'cardiologia' GROUP BY Pazienti.Nome HAVING COUNT(*) > 1;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'cardiologia' GROUP BY Pazienti.Nome HAVING COUNT(*) > 1;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.Diagnosi LIKE '%cancro%' GROUP BY Pazienti.Nome HAVING COUNT(*) > 1;
SELECT DISTINCT Ricoveri.ID_paziente FROM Ricoveri GROUP BY Ricoveri.ID_paziente HAVING COUNT(*) > 1;
SELECT Medici.Nome, Medici.Specializzazione FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome HAVING COUNT(Ricoveri.ID_paziente) > 5;
SELECT Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Reparti.nome_reparto = 'emergenza' GROUP BY Pazienti.Nome HAVING COUNT(*) > 1;
SELECT strftime('%Y', Ricoveri.Data_ricovero) AS Anno, Reparti.nome_reparto, COUNT(*) AS NumeroPrescrizioni FROM Farmaci JOIN Ricoveri ON Farmaci.ID_ricovero = Ricoveri.ID_ricovero JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto WHERE Farmaci.Descrizione = 'diazepam' GROUP BY Anno, Reparti.nome_reparto;
SELECT Ricoveri.Diagnosi, GROUP_CONCAT(Farmaci.Descrizione) AS Farmaci FROM Ricoveri JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero GROUP BY Ricoveri.Diagnosi HAVING COUNT(Ricoveri.ID_ricovero) > 1;
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico WHERE strftime('%Y', Ricoveri.Data_ricovero) BETWEEN '2022' AND '2023' GROUP BY Medici.Nome HAVING COUNT(Ricoveri.ID_paziente) > 3;
SELECT Medici.Nome FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome HAVING COUNT(Ricoveri.ID_paziente) > 5;
SELECT Medici.Nome, Pazienti.Nome AS Paziente, Reparti.nome_reparto, Ricoveri.Diagnosi, GROUP_CONCAT(Farmaci.Descrizione) AS Farmaci FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Pazienti ON Ricoveri.ID_paziente = Pazienti.ID_paziente JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero WHERE (julianday(Ricoveri.Data_dimissione) - julianday(Ricoveri.Data_ricovero)) = (SELECT MAX(julianday(Data_dimissione) - julianday(Data_ricovero)) FROM Ricoveri) GROUP BY Medici.Nome, Pazienti.Nome, Reparti.nome_reparto, Ricoveri.Diagnosi;
SELECT Medici.Nome, Reparti.nome_reparto, Medici.Nome AS CapoReparto FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Reparti ON Ricoveri.ID_reparto = Reparti.ID_reparto GROUP BY Reparti.nome_reparto, Medici.Nome;
SELECT Reparti.nome_reparto, Medici.Nome AS CapoReparto, COUNT(Ricoveri.ID_ricovero) AS NumeroAmmissioni FROM Reparti JOIN Medici ON Reparti.direttore_reparto = Medici.ID_medico JOIN Ricoveri ON Reparti.ID_reparto = Ricoveri.ID_reparto GROUP BY Reparti.nome_reparto, Medici.Nome HAVING COUNT(Ricoveri.ID_ricovero) > 3;
SELECT Pazienti.Nome, Pazienti.Indirizzo FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome, Pazienti.Indirizzo HAVING COUNT(Ricoveri.ID_ricovero) > 2;
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome, Ricoveri.Data_ricovero HAVING COUNT(DISTINCT Ricoveri.ID_reparto) > 1;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome, Pazienti.Numero_di_telefono HAVING COUNT(DISTINCT Ricoveri.ID_medico) > 1;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome, Pazienti.Numero_di_telefono HAVING COUNT(DISTINCT Ricoveri.ID_reparto) > 1;
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome, Medici.Email HAVING COUNT(DISTINCT Ricoveri.Diagnosi) > 1;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome HAVING COUNT(DISTINCT Ricoveri.ID_medico) > 3;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome HAVING COUNT(DISTINCT Ricoveri.ID_reparto) > 1;
SELECT Medici.Nome, Medici.Specializzazione FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome HAVING COUNT(DISTINCT Ricoveri.ID_reparto) > 1;
SELECT Reparti.nome_reparto, COUNT(*) AS NumeroAmmissioni FROM Reparti JOIN Ricoveri ON Reparti.ID_reparto = Ricoveri.ID_reparto WHERE strftime('%Y', Ricoveri.Data_ricovero) IN ('2022', '2023') GROUP BY Reparti.nome_reparto HAVING COUNT(*) > 10;
SELECT Medici.Nome FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome HAVING COUNT(Ricoveri.ID_paziente) > 5;
SELECT Pazienti.Nome, Ricoveri.Diagnosi FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.Diagnosi LIKE '%diabete%' GROUP BY Pazienti.Nome HAVING COUNT(Ricoveri.Diagnosi) > 2;
SELECT Medici.ID_medico, Medici.Nome, Medici.Email, Medici.Telefono, COUNT(*) AS NumeroScansioni FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico JOIN Procedure ON Ricoveri.ID_ricovero = Procedure.ID_ricovero WHERE Procedure.Descrizione LIKE '%CT%' OR Procedure.Descrizione LIKE '%MRI%' GROUP BY Medici.ID_medico ORDER BY NumeroScansioni DESC LIMIT 1;
SELECT * FROM Medici WHERE Medici.ID_medico = (SELECT Medici.ID_medico FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.ID_medico ORDER BY COUNT(Ricoveri.ID_paziente) DESC LIMIT 1);
SELECT Pazienti.Nome, Ricoveri.Data_ricovero FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome HAVING COUNT(DISTINCT Ricoveri.ID_reparto) > 1 AND COUNT(DISTINCT strftime('%Y', Ricoveri.Data_ricovero)) = 1;
SELECT Pazienti.Nome, Pazienti.Data_nascita, Medici.Nome AS Medico FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico WHERE Ricoveri.Diagnosi LIKE '%diabete%' GROUP BY Pazienti.Nome, Pazienti.Data_nascita HAVING COUNT(Ricoveri.Diagnosi) > 1;
SELECT Medici.Nome, Medici.Email FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome, Medici.Email HAVING COUNT(Ricoveri.ID_paziente) > 2 ORDER BY Reparti.nome_reparto, COUNT(DISTINCT Pazienti.Genere);
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente GROUP BY Pazienti.Nome HAVING COUNT(DISTINCT Ricoveri.ID_medico) >= 2;
SELECT Pazienti.Nome, Pazienti.Numero_di_telefono FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente WHERE Ricoveri.ID_medico IN (SELECT ID_medico FROM Medici WHERE Nome IN ('Daniel Lee', 'Lily Baker')) GROUP BY Pazienti.Nome HAVING COUNT(DISTINCT Ricoveri.ID_medico) >= 2;
SELECT Pazienti.Nome, Medici.Nome AS Medico FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Medici ON Ricoveri.ID_medico = Medici.ID_medico GROUP BY Pazienti.Nome HAVING COUNT(*) > 3;
SELECT Pazienti.Nome, GROUP_CONCAT(Farmaci.Descrizione) AS Farmaci FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Farmaci ON Ricoveri.ID_ricovero = Farmaci.ID_ricovero WHERE Farmaci.Descrizione LIKE '%antibiotico%' GROUP BY Pazienti.Nome HAVING COUNT(Farmaci.Descrizione) > 1;
SELECT Pazienti.Nome FROM Pazienti JOIN Ricoveri ON Pazienti.ID_paziente = Ricoveri.ID_paziente JOIN Procedure ON Ricoveri.ID_ricovero = Procedure.ID_ricovero GROUP BY Pazienti.Nome HAVING COUNT(Procedure.Descrizione) > 1;
SELECT Farmaci.Descrizione, COUNT(*) AS Frequenza FROM Farmaci WHERE strftime('%Y', Farmaci.Data_prescrizione) = '2023' GROUP BY Farmaci.Descrizione ORDER BY Frequenza DESC LIMIT 1;
SELECT Farmaci.Descrizione, COUNT(*) AS Frequenza FROM Farmaci WHERE strftime('%Y', Farmaci.Data_prescrizione) = '2023' GROUP BY Farmaci.Descrizione ORDER BY Frequenza DESC LIMIT 1;
SELECT Medici.Nome, COUNT(Ricoveri.ID_paziente) AS NumeroAmmissioni FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome HAVING COUNT(Ricoveri.ID_paziente) = (SELECT MAX(NumeroAmmissioni) FROM (SELECT Medici.Nome, COUNT(Ricoveri.ID_paziente) AS NumeroAmmissioni FROM Medici JOIN Ricoveri ON Medici.ID_medico = Ricoveri.ID_medico GROUP BY Medici.Nome));